version: '3.8'
services:
  app:
    container_name: 'php-apache'
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
        - db
    volumes:
      - ./happs:/var/www/html
    ports:
      - 80:80
    networks:
      - laravel-app
  db:
    container_name: db
    image: 'mariadb:10.2.8'
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
    volumes:
      - ./datadir:/var/lib/mysql
    ports:
      - '${DB_PORT}:3306'
    networks:
      - laravel-app

networks:
    laravel-app:
        driver: bridge